### PR TITLE
Reset global timeouts after the request finishes

### PR DESCRIPTION
**Pull request by zanker**
:(

Hat tip to @RickCSong for spotting this.

### CODE REVIEW

**Comment by sferik** [comment]
:+1:

**Comment by sferik** [comment]
Nice catch.

**Comment by ixti** [comment]
@zanker any objections if I will cut 0.8.6 gem?

**Comment by ixti** [comment]
Or you can cut yourself (I have updated readme to reflect changes ;))

**Comment by ixti** [comment]
Ah.. Somebody cut it before I thought of it ;))

**Comment by RickCSong** [comment]
:+1: Yay!

**Pull request merged**
