### PR TITLE
Support SNI for HTTPS connections

### PR DESCRIPTION
**Pull request by tarcieri**

### CODE REVIEW

**Comment by zanker** [comment]
OOPS

Forgot to set that...

**Comment by tarcieri** [comment]
cc @zanker @ixti

**Comment by somethingnew2-0** [comment]
Thanks @tarcieri!

**Comment by tarcieri** [comment]
Build failures look unrelated. Do you agree @zanker ?

**Comment by tarcieri** [comment]
Released as http.rb 0.8.11

**Comment by zanker** [comment]
Yea those build failures definitely look unrelated, just transient

**Pull request merged**
