### PR TITLE
Use at_exit instead of overriding trap for interrupt to shutdown ProxyServer, AuthenticatedProxyServer

### PR DESCRIPTION
**Pull request by olegkovalenko**
Call to trap replaces handler for specified signal,
so ProxyServer.shutdown would have never been called.
at_exit registers handler for execution when the programm
exits, handlers are executed in revers order of registration.

### CODE REVIEW

**Comment by tarcieri** [comment]
Hmm, I think the best solution here is to factor ProxyServer startup/shutdown into before/after blocks...

**Comment by ixti** [comment]
Although this patch really makes things a bit better, it doesn't fixes same issue with example_server, and I agree with @tarcieri it's better to start/stop it with before/after blocks.

**Comment by ixti** [comment]
I have re-factored how we start `ExampleServer` (also renamed it to `DummyServer`) in specs.
You can check new implementation and kind of follow same way if you want, or I will jump on this later.

**Comment by ixti** [comment]
Ouch. My last commit broke your last commit :D

Please, don't put before blocks into `spec_helper`.
Instead add `RSpec.configure do |config|` to the end of `proxy_server` with your code.
And remove `ExampleServer` start out of there - I have completely refactored it.

**Comment by olegkovalenko** [comment]
No worries ;)

**Comment by tarcieri** [comment]
Typically I start and stop these sorts of things in conjunction with the tests that depend on them, rather than globally in the suite.

**Comment by ixti** [comment]
Thanks for your PR, but I have implemented it in a bit different way :D
In any case thank you very much.

**Comment by olegkovalenko** [comment]
(handshake)
Thanks you for time and suggestions ;)

**Pull request closed without merging**
