### PR TITLE
This should address issue 112

### PR DESCRIPTION
**Pull request by hiromipaw**
After a quick chat on Friday with @ixti, thought to address issue 112: https://github.com/httprb/http.rb/issues/112
Please let me know if I haven't understood the specs correctly and if anything is missing.

### CODE REVIEW

**Comment by sferik** [comment]
Overall, this looks good. However, it pushes the `#follow` method over our complexity metric, which causes the build to fail. Can you please refactor in such a way that RuboCop doesn’t complain? To check the complexity locally, you can run the following command from the `http.rb` project directory.

```
bundle exec rubocop lib/http/redirector.rb
```

**Comment by hiromipaw** [comment]
Sure I will refactor and push back.

**Comment by ixti** [comment]
@hiromipaw Thank you very much. I'll review PR later this week.

**Comment by ixti** [comment]
Thanks again. I have merged your commits into my branch:
https://github.com/httprb/http.rb/tree/improvement/redirector-logic

Gonna improve couple of more things and will merge it to master.
Thanks again!

**Pull request closed without merging**
