### PR TITLE
Revert Caching (#177) (fixes #239)

### LINKED ISSUE #239: Delegation issues in HTTP::Request::Caching
While investigating jruby/jruby#3151, a few issues with the way `Caching` does delegation came to light:

* At least one place, in `conditional_on_changes_to`, an `HTTP::Request` object gets double-delegated. Both the `self.class.new` and `.caching` calls wrap the new `HTTP::Request` object in a delegating `Caching` instance.
* The `Caching` class itself is created before `HTTP::Request` has completed loading, resulting in a `DelegateClass` that does most delegation through `method_missing` rather than through generated, direct delegation methods.

These issues are not strictly bugs, but they likely affect performance. In the case of jruby/jruby#3151, they also exposed an obscure bug in JRuby.

### PR DESCRIPTION
**Pull request by tarcieri**
Reverts support for client-side caching using rack-cache, added here:

https://github.com/httprb/http.rb/pull/177

There have been ongoing maintenance problems with this code
(e.g. fd0484724e949ab9effb4c6a13ab9c6fdb3ff2a3) and it's also implicated in
breakages and performance problems on JRuby 9000:

https://github.com/httprb/http.rb/issues/239

### CODE REVIEW

**Comment by tarcieri** [comment]
Heads up @pezra. We've been having a lot of problems with this code lately and we're not sure it's actually worth keeping, at least in its current form. I was a fan of Resourceful and excited to see this land, but as someone who's not using it and only dealing with the maintenance I'm not sure it's worth keeping.

I think it might make more sense as a separate gem, provided you can get some decent hooks into http.rb to do so.

**Comment by tarcieri** [comment]
This might also warrant a version bump if we land it (0.9.0?) I know there was some other stuff on the roadmap for that milestone, but it seems like a big enough change to warrant a minor version change.

**Comment by zanker** [comment]
LGTM, agree on bumping to 0.9.0 due to breaking changes.

**Comment by tarcieri** [comment]
Confirmed #239 is fixed: build is now passing on JRuby 9000

**Comment by pezra** [comment]
I must say I'm a little disappointed to have it reverted wholesale without even a chance to try to salvage it. I think the internal design of http.rb makes it pretty much impossible to implement caching as a gem without monkey patching way more than is advisable.

Fwiw, an http client without caching is pretty much useless to me. I guess resourceful is still an option. :neutral_face:

**Comment by ixti** [comment]
@pezra PR is not yet merged. The only way of salvation I see is refactoring the whole thing to get rid of `rack-cache`. I agree that current internals are not perfect to have cache support completely as a separate gem, but it's possible to find a way to make it transparent and lightweight.

**Comment by ixti** [comment]
@tarcieri @zanker I think we can move exisitng `0.9` issues to `0.10`, and release cache-less version as `0.9`.

**Comment by pezra** [comment]
@ixti, is rack cache the main problem or is it the issues described in #239? I think removing the dependency on rack is doable. (Probably by extracting the storage bits of rake-cache into a separate gem.) The things in #239 all look worth solving and i'd be happy to work on them. (But of course my time is somewhat constrained). 

I will think about how we might enable an external caching gem.

**Comment by ixti** [comment]
@pezra the problem is complex. :D `rack-cache` dependency is one bit of it. I understand time is not elastic. And I was also hoping to get my hands on improvements of cache layer - but absolutely out of time (summer time - kids are not in school). And sometimes it worth destroy legacy to build something new. In other words `http.rb` will have cache support again some time later :D

**Comment by zanker** [comment]
To step back a little, what do you need innate caching support for @pezra? It seems like something you could implement on top of http.rb without much issue. Even if it's just a wrapper around it, and it'd be a lot simpler.

**Comment by tarcieri** [comment]
> I must say I'm a little disappointed to have it reverted wholesale without even a chance to try to salvage it. 

@pezra well, this is the scorched earth option. We can explore others.

But like @zanker I wonder if this sort of functionality could be layered on top of http.rb rather than having to be inside of it.

**Comment by tarcieri** [comment]
So it looks like JRuby 9000 is out:

http://blog.jruby.org/2015/07/jruby_9000/

I'm going to land this for now and release it as 0.9.0.pre

@pezra if you're interested in fixing things up so they work on JRuby 9000 again, we can revert the "revert" and bring caching back.

**Comment by tarcieri** [comment]
I just deployed this in a JRuby 9000 app today and everything is looking good.

Unless there's any objections, I'd like to cut a 0.9.0 release tomorrow with JRuby 9000 support.

**Comment by tarcieri** [comment]
@pezra happy to circle back with you and address the issues so we can get this back in. Perhaps we can find some better hooks so you don't need to use `delegate.rb` for this.

**Comment by pezra** [comment]
OK. Some extension mechanisms and an external gem seem to be the best approach since the http.rb community is not interested in maintaining caching functionality. I'll take a look at what it would take to make that happen as time permits. For now i'll just lock all my projects to 0.8. :disappointed:

**Comment by pezra** [comment]
@zanker, @tarcieri, I don't see how it can be implemented as wrapper. *Any* header can affect the cache lookup (see `Vary` header) so the cache needs to have the request with all the headers that will be put on the wire. 

Also, we don't want to bypass the cache when following redirections.

**Comment by tarcieri** [comment]
@pezra we'd like to add some (optional) hooks to the request/response lifecycle. See #209

**Comment by pezra** [comment]
@tarcieri, that looks like it might be able support an add-on cache system. i'll continue this discussion on that issue.

**Comment by zanker** [comment]
@pezra Sorry, I'm still not quite sure what you mean. Why wouldn't:

```ruby
class CachedHttpRb
  def initialize(httprb)
    @httprb = httprb
  end
  
  def get(path)
    if @response && @response.headers['Expires'] > Time.now
      return @response
    end
  
    @response = @httprb.get(path)
  end
end
```

As a rough example?

**Comment by pezra** [comment]
@zanker, consider the following scenario: 

A rails app that
 1. receives requests with a bearer token authorization header
 2. creates a new httprb based on that bearer token and wraps in a simple cacher
 3. makes requests against other servers on behalf of the user
 4. ...

Step 3 almost certainly returns a cached response intended for an earlier user. This is only a problem if the cache store is shared between requests but the cache would be pretty unhelpful it that were not the case.

This same sort of issue applies to `Accept`, `Cookie`, `Prefer` and any number of other header fields, all of which would likely be set below the caching wrapper.

**Comment by jrochkind** [comment]
Hmm, I'm super interested in this feature, sad to find it was here but left along time ago. 

I wonder if I can reintroduce it as third-party code, does http have any kind of plug-in middleware architecture that might let me add it back?

**Comment by tarcieri** [comment]
@jrochkind #482 added something which may be applicable /cc @paul

**Comment by jrochkind** [comment]
Not sure if the "observers" (at present?) will let something interupt a request and substitute a response without the client ever going out to the network?  

I also see that #223 is still open... not sure if you mean it to be. :)

**Comment by paul** [comment]
@jrochkind I think what you're looking for is #482. It needs a small change to `available_features` (https://github.com/httprb/http/blob/master/lib/http/options.rb#L25) to allow additional features to be inserted, but it should be possible to add an HTTP cache as a "Feature" like this. (well, maybe. Now that I look at it, I guess you can't halt the request and substitute a response from a cache without some additional changes to the API. Maybe `Client#build_request` can check if any of the features returned a `Response` instead of a `Request`, and just use that...)

**Comment by pezra** [comment]
@paul, can caching actually be built as a `Feature`? features don't seems to be able to prevent the request from being put on the wire. perhaps that is a forthcoming capability of features?

i sure hope so. i'd love to be able to upgrade from version 0.8.

**Comment by pezra** [comment]
@paul, or a `Feature` could, optionally, wrap the connection too.

**Comment by tarcieri** [comment]
@paul definitely curious about ways we could extend the feature to further control the request flow

**Pull request merged**
