### PR TITLE
Include JRuby 1.7 as a supported version

### PR DESCRIPTION
**Pull request by zanker**
Thoughts? I'm going to end up having to maintain this for JRuby incidentally anyway, so might as well include it as an officially supported language.

### CODE REVIEW

**Comment by ixti** [comment]
If you are going to support it, then it worth to add to `.travis.yml`:

``` yaml
# ...
rvm:
  - 1.9.3
  # ...
  - jruby-19mode
#...
```

**Comment by zanker** [comment]
Good point, done

**Comment by ixti** [comment]
Please, squash PR into a single commit.
@tarcieri LGTM

**Comment by ixti** [comment]
Oh I just figured out that `-jruby` and `-jruby-19mode` are the same... Sorry. Seems like only first of your commits was needed.

**Comment by ixti** [comment]
Sorry, 3:48am.. I'm a bit slow :D
Closed via https://github.com/httprb/http.rb/commit/cb3c9b1d3c45e81b71258b35cbca949bc508f42e

**Pull request closed without merging**
