### PR TITLE
Added Keep-Alive timeouts to auto reset connections

### PR DESCRIPTION
**Pull request by zanker**
This is in net-http-persistent too and as far as I can tell it's kind of necessary.

Adds a timeout so if the connection isn't used for more than X seconds, it automatically restarts it.

### CODE REVIEW

**Comment by sferik** [comment]
Rubbocopped!

**Comment by zanker** [comment]
Bahhhhhhhhh fixed

**Comment by sferik** [comment]
:+1:

**Comment by zanker** [comment]
Yea this was the last bit of bug fixes we needed to get persistent conns working. @tarcieri or @sferik mind merging/releasing a 0.8.0.pre2 please?

**Comment by tarcieri** [comment]
master released as 0.8.0.pre2

**Comment by tarcieri** [comment]
Okay, let's try that again. With this PR merged, master released as 0.8.0.pre3

**Comment by sferik** [comment]
I moved all of the open issues and pull requests into the [v0.8 milestone](https://github.com/httprb/http.rb/milestones/v0.8) and created a [v0.9 milestone](https://github.com/httprb/http.rb/milestones/v0.9) with a target date of May 1, pushing back the [v1.0 milestone](https://github.com/httprb/http.rb/milestones/v1.0) to June 1. Anything that doesn’t make it into the v0.8 release can be moved to v0.9. IMHO, there’s too much public interface churn to responsibly release v1.0. I would like to see things settle down a bit and make sure all the edge cases are worked out before shipping v1.0.

**Comment by tarcieri** [comment]
We're looking at using this gem internally at Square, which has been the motivator for a lot of the recent changes. We can hopefully iterate on the API deficiencies quickly and get to 1.0.

**Comment by sferik** [comment]
Does Square have a policy against running < 1.0 code in production? My concern about rushing to release v1.0 is that we’d find design mistakes and want to release v2.0 shortly thereafter. I think it’s better to do that iteration in 0.x versions and only release 1.0 after a period of stability.

**Comment by tarcieri** [comment]
There's no rush, I'm just saying that we'll have more eyes on it and can probably help accelerate its development.

**Pull request merged**
